### PR TITLE
R: Generate summary tables

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Generates 4 summary files with tabular data.

Is the error propagation for the stdev correct?

### CODE REVIEW

**Comment by sbesson** [comment]
A few initial comments:

- we will need to make sure our metrics are clarified in the supplementary material and the readme of this repo e.g. Performance being defined as one over the execution time, pixels performance as the pixels size/complexity over the execution time and metadata performance as the metadata size/complexity over the execution time. Is `performance` the right attribute here?
- with regard to the definition of metadata performance, using the total number of elements is certainly the closest to the reality. On the other side, it creates yet another dimensioned units while using the metadata size would give numbers "comparable" to the pixels performance
- the error propagation looks good to me, as both the pixels and metadata size/complexity have no error, the log of the performance scales linearly with the log of the execution time and thus

  ```
  delta_performance / performance = delta_execution_time / execution_time
  ```

Looking at the metrics into more details

**Comment by rleigh-codelibre** [comment]
@sbesson Now includes summary data and plots.

I've added to the summary tables:

- metadata rates in MiB/s
- metadata rates in kiloelements/s
- pixeldata rates in MiB/s

Is the error propagation still OK?  I'm making the assumption that the sdratio is scale-independent when scaling by 10^3

Note some of the pixeldata rates are very high.  Likely caching on read.  On write, might be timing granularity for small datasets if we don't fully flush (since we time the close separately).  This is one place where profiling the minimal tiff reader would test without the complication of separating out metadata.  We could add an explicit `TIFFFlushData()` call here to ensure it's all written and synched to disc during the pixeldata timing points.

Note that we don't expose flushing or contained open TIFF files at the writer level, making it impossible to insert a flush without API additions.  For this reason, we might want to include the aggregate measurement or replace the pixel data with the aggregate measurements so that we don't report pixel data which is unflushed.  Alternatively, we could subtract metadata from aggregate to get pixeldata timings (assuming all non-metadata overhead is pixeldata)

Statistics now use "rates" rather than performance.  Plots can be updated; any preferred name to replace "Performance ratio"?

**Comment by sbesson** [comment]
Looking at the inline comment in the scripts vs the last comment, the metadata rates are expressed in `MiB/s` or `KiB/s`?

With regard to semantics, I tried to define the metrics in https://github.com/openmicroscopy/ome-files-performance/pull/32. `Metadata rate` and `Pixeldata rate` make sense to me. With regard to `Performance ratio`, another proposal would be `Relative performance` used commonly in benchmarking it seems.

**Comment by rleigh-codelibre** [comment]
Everything is now MiB/s.

For "Relative performance", do we want to invert the y axis by taking the reciprocal value so that bigger is better?

**Comment by rleigh-codelibre** [comment]
Updated plot axis labels and titles; is this OK?

**Pull request merged**
