### PR TITLE
Add C++ strip and tile benchmark

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
This isn't directly equivalent to David's benchmark--that will come later.  This is a test to profile the tiling performance of the TIFF wrapper code directly, not using the FormatWriter API (which isn't yet merged).  This will let us profile the optimal strip and tile sizes on a number of different platforms.

### CODE REVIEW

**Comment by sbesson** [comment]
Discussed with @rleigh-codelibre. I got confused by the name and the intent of the benchmark confused me as well as the initial requirements in terms of disk space. Proposed next immediate actions are to: 

- reduce the  space required by this benchmarking by removing the largest pixel types (292abfb) and trying to free up space the in between iterations when possible
- execute this C++ benchmark in `beluga`
- port the Java [tiling API](https://github.com/openmicroscopy/ome-files-performance/pull/44) class to C++ with the new API and run them against the reference datasets (`tubhiswt`, `neff-histopathology`) for comparison

Once this is done we might need to focus on:
- reciprocally porting this low-level benchmark to Java to test the TIFF writing component
- deciding how to name these 2 types of tiling benchmarks to clearly understand the intent
- deriving the analysis and graphs from the execution results

A much longer term thought was to eventually refactor some of these benchmarks as some kind of ome-files diagnostics utility.

**Comment by rleigh-codelibre** [comment]
@sbesson Should now clean files up more frequently, which should keep disc usage to a manageable level.  Should be ready to test.

**Comment by sbesson** [comment]
For reference, I have started the execution of the latest state of this branch on `beluga` using  `/temporary/benchmarks/` as the location for the output data (temporary images, tabular results, execution log):

```
$ docker pull snoopycrimecop/ome-files-performance:master_merge_trigger
$ docker run --rm -it --entrypoint=bash  -v  /temporary/benchmarks:/data snoopycrimecop/ome-files-performance:master_merge_trigger
# ./scripts/run_cpp_tile_benchmarking >> /data/log 2>&1

```

Benchmarks are still running after 24h of execution with hopefully the complete results available tomorrow morning. Is the total execution time expected as a result of the number of iterations (10) and the number of benchmark combinations?

**Comment by rleigh-codelibre** [comment]
@sbesson The results of the weekend analysis are attached.  Nothing too unsurprising there.  Six PDFs added under `analysis`.

Note the noise in the performance graphs.  Likely due to the lack of fsync causing inconsistencies between iterations; but may also be that running on docker and contending with other users is also a factor.  It's not a good setup for benchmarking in general.  But getting fsync support added to formatwriter would likely correct a large part of the variance.

**Comment by dgault** [comment]
The code for the tests looks good and is well structured and easy to read and extend if needed. The actual test parameters look sensible to me and give a good indication of the write performance and file sizes.

The results look to be pretty much as expected with the Pixel Type playing a big factor. It doesn't look like the size plays a major factor other than for the very small tile sizes. Otherwise the same overlap pattern as I initially saw is apparent in the file size results which also makes sense.

As a low level test this achieves what it was intended to, it should be straightforward to port this to Java if we wish to benchmark the low level Tiff writing there also.

**Comment by sbesson** [comment]
Thanks  for the thorough review @dgault. While @rleigh-codelibre ports the existing `FormatWriter` tiling benchmark, this benchmark will be renamed to avoid conflicts as the scope is more focused on TIFF writing.

Porting this benchmark to Java would certainly be a good thing to mirror the C++ behavior. My proposal would be to do that as a validation of the decoupled TIFF components planned for the upcoming weeks.

Merging this PR so that we can also start cleaning and organization the description and results to reflect the existing of multiple benchmarks.

**Pull request merged**
