### PR TITLE
Add JACE tests

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Duplicates of the existing C++ and Java tests, using JACE.

I've had to import some of the generated bits from bio-formats-jace due to it not packaging them.

Testing:

- build bio-formats-jace
- run cmake, with CMAKE_PREFIX_PATH including the bio-formats-jace dist/bio-formats-jace directory; it should autodetect bio-formats-jace
- build
- copy the bio-formats-jace `jar` directory into the build directory (maybe could be added to `CLASSPATH`?)
- run the examples as for the existing C++ tests

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
The pixels-performance test throws an exception when writing the TIFF comment.  I've not been able to pin down why this happens; the metadata store is filled correctly and written out correctly, but at the start of the TIFF.  Could anything in the environment/classpath alter the TiffSaver behaviour here?

**Comment by sbesson** [comment]
--exclude

**Comment by sbesson** [comment]
As we are currently using the Windows builds to assess the effect of the latest performance fixes for Java vs C++ and in order to simplify the review of this PR, would it be possible to update the `Dockerfile` to document the required steps i.e. cloning and building `bio-formats-jace`, running the `cmake` command and running the examples in the `run_benchmarking` scripts? You might need to use a different JDK as the default Java on Ubuntu is Java8 (I assume there is a PPA?)

**Comment by rleigh-codelibre** [comment]
I'm using the JDK7 downloaded from Oracle.

Regarding the Dockerfile, not sure on what needs doing there but I was going to write the steps into the jenkins-build.bat to document the process.

**Comment by sbesson** [comment]
Fair enough, I had forgotten the fact Ubuntu 16.04 does not ship openjdk7 anymore. The Oracle JDK requirement certainly makes the Docker strategy less portable.

Falling back to Windows as the primary operating system for conducting the JACE tests, https://ci.openmicroscopy.org/job/OME-FILES-performance-win/ has been modified to:

- change `JAVA_HOME` to use JDK 7_LATEST instead of 8_LATEST
- clone `bio-formats-jace` under the workspace (`$WORKSPACE/bio-formats-jace`)

Can you push the corresponding build steps to `jenkins-build.bat` so we can the JACE is built and exectued as part of the performance builds?

**Comment by sbesson** [comment]
I have some changes on top of this branch updating the `Dockerfile` and was able to build the JACE bindings successfully. Thanks. Merging and we can keep the discussion on the following PR.

**Pull request merged**
