### PR TITLE
Test Bio-Formats 5.3.3

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Update dependencies to build against bio-formats 5.3.3

### CODE REVIEW

**Comment by sbesson** [comment]
NB: this depends on https://github.com/ome/bio-formats-jace/pull/8. Excluding for now to review #13 and #14

**Comment by sbesson** [comment]
@rleigh-codelibre could you update https://github.com/openmicroscopy/ome-files-performance/blob/master/Dockerfile#L13 to point at your branch of `bio-formats-jace` ? That way we can test both PRs using the benchmarking scripts.

**Comment by sbesson** [comment]
Should https://github.com/openmicroscopy/ome-files-performance/blob/master/CMakeLists.txt#L67 also be updated to find Bio-Formats JACE 5.3.0 as per https://github.com/ome/bio-formats-jace/pull/8/files#diff-600376dffeb79835ede4a0b285078036L9 ?

**Comment by rleigh-codelibre** [comment]
Yes, it will need updating once this is merged.

**Comment by sbesson** [comment]
https://github.com/ome/bio-formats-jace/pull/8 is in, can you update `CMakeLists.txt` @rleigh-codelibre ?

**Comment by rleigh-codelibre** [comment]
@sbesson See https://github.com/openmicroscopy/ome-files-performance/pull/18

**Pull request merged**
