### PR TITLE
Use C++11 standard library features

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Replace use of boost and ome::compat now we are building against 0.3.0.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-FILES-performance-merge#52](https://ci.openmicroscopy.org/job/OME-FILES-performance-merge/52/). See the [console output](https://ci.openmicroscopy.org/job/OME-FILES-performance-merge/52/consoleText) for more details.
Possible conflicts:
  - PR #13 rleigh-codelibre 'Delete output file if it exists before writing'
    - src/main/jace/pixels-performance.cpp
  - PR #15 rleigh-codelibre 'Test Bio-Formats 5.3.3'
    - src/main/jace/pixels-performance.cpp
  - Upstream changes
    - src/main/jace/pixels-performance.cpp

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-FILES-performance-merge#53](https://ci.openmicroscopy.org/job/OME-FILES-performance-merge/53/). See the [console output](https://ci.openmicroscopy.org/job/OME-FILES-performance-merge/53/consoleText) for more details.
Possible conflicts:
  - PR #13 rleigh-codelibre 'Delete output file if it exists before writing'
    - src/main/jace/pixels-performance.cpp
  - Upstream changes
    - src/main/jace/pixels-performance.cpp

**Comment by sbesson** [comment]
@rleigh-codelibre you should be able to resolve the conflicts on this PR now that #13 is merged.

**Comment by rleigh-codelibre** [comment]
@sbesson Done

**Review by mtbc — APPROVED** [review]

**Comment by sbesson** [comment]
```
Step 19 : RUN cmake -DCMAKE_INSTALL_PREFIX:PATH=/install   -DCMAKE_CXX_STANDARD=11   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_PREFIX_PATH="$OME_FILES_BUNDLE;$BF_JACE_HOME"   -DCMAKE_PROGRAM_PATH=$OME_FILES_BUNDLE/bin   -DCMAKE_LIBRARY_PATH=$OME_FILES_BUNDLE/lib   /git/ome-files-performance
 ---> Running in 30787d90e35b
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CXX_FLAG-pedantic
-- Performing Test CXX_FLAG-pedantic - Success
-- Performing Test CXX_PEDANTIC_LONG_LONG
-- Performing Test CXX_PEDANTIC_LONG_LONG - Success
-- Performing Test CXX_FLAG_Wall
-- Performing Test CXX_FLAG_Wall - Success
-- Performing Test CXX_FLAG_Wcast_align
-- Performing Test CXX_FLAG_Wcast_align - Success
-- Performing Test CXX_FLAG_Wcast_qual
-- Performing Test CXX_FLAG_Wcast_qual - Success
-- Performing Test CXX_FLAG_Wctor_dtor_privacy
-- Performing Test CXX_FLAG_Wctor_dtor_privacy - Success
-- Performing Test CXX_FLAG_Wextra
-- Performing Test CXX_FLAG_Wextra - Success
-- Performing Test CXX_FLAG_Wformat_2
-- Performing Test CXX_FLAG_Wformat_2 - Success
-- Performing Test CXX_FLAG_Wimplicit_atomic_properties
-- Performing Test CXX_FLAG_Wimplicit_atomic_properties - Failed
-- Performing Test CXX_FLAG_Wmissing_declarations
-- Performing Test CXX_FLAG_Wmissing_declarations - Success
-- Performing Test CXX_FLAG_Wno_long_long
-- Performing Test CXX_FLAG_Wno_long_long - Success
-- Performing Test CXX_FLAG_Wnon_virtual_dtor
-- Performing Test CXX_FLAG_Wnon_virtual_dtor - Success
-- Performing Test CXX_FLAG_Woverlength_strings
-- Performing Test CXX_FLAG_Woverlength_strings - Success
-- Performing Test CXX_FLAG_Woverloaded_virtual
-- Performing Test CXX_FLAG_Woverloaded_virtual - Success
-- Performing Test CXX_FLAG_Wredundant_decls
-- Performing Test CXX_FLAG_Wredundant_decls - Success
-- Performing Test CXX_FLAG_Wreorder
-- Performing Test CXX_FLAG_Wreorder - Success
-- Performing Test CXX_FLAG_Wswitch_default
-- Performing Test CXX_FLAG_Wswitch_default - Success
-- Performing Test CXX_FLAG_Wunused_variable
-- Performing Test CXX_FLAG_Wunused_variable - Success
-- Performing Test CXX_FLAG_Wwrite_strings
-- Performing Test CXX_FLAG_Wwrite_strings - Success
-- Performing Test CXX_FLAG_Wno_variadic_macros
-- Performing Test CXX_FLAG_Wno_variadic_macros - Success
-- Performing Test CXX_FLAG_fstrict_aliasing
-- Performing Test CXX_FLAG_fstrict_aliasing - Success
-- Performing Test OME_HAVE_SNPRINTF
-- Performing Test OME_HAVE_SNPRINTF - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   system
--   iostreams
--   log
--   log_setup
--   program_options
--   regex
--   thread
--   atomic
-- Performing Test OME_VARIANT_LIMIT
-- Performing Test OME_VARIANT_LIMIT - Failed
-- Found XercesC: /usr/lib/x86_64-linux-gnu/libxerces-c.so (found version "3.1.3") 
-- Found XalanC: /usr/lib/x86_64-linux-gnu/libxalan-c.so (found version "1.11.0") 
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.6") 
-- JACE: HDR bio-formats-jace-5.2.1.h
-- Found BioFormatsJACE: /build-jace/dist/bio-formats-jace/libbio-formats-jace.so (found suitable version "5.2.1", minimum required is "5.2.1") 
-- Found JNI: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjawt.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /build-ome-files
 ---> 14dedf03cc25
Removing intermediate container 30787d90e35b
Step 20 : RUN cmake --build .
 ---> Running in f86ed75784d3
Scanning dependencies of target metadata-performance
[  1%] Building CXX object src/main/cpp/CMakeFiles/metadata-performance.dir/metadata-performance.cpp.o
[  2%] Building CXX object src/main/cpp/CMakeFiles/metadata-performance.dir/result.cpp.o
[  3%] Linking CXX executable metadata-performance
[  3%] Built target metadata-performance
Scanning dependencies of target pixels-performance
[  4%] Building CXX object src/main/cpp/CMakeFiles/pixels-performance.dir/pixels-performance.cpp.o
/git/ome-files-performance/src/main/cpp/pixels-performance.cpp: In function 'int main(int, char**)':
/git/ome-files-performance/src/main/cpp/pixels-performance.cpp:118:27: error: 'make_unique' is not a member of 'std'
                     buf = std::make_unique<ome::files::VariantPixelBuffer>
                           ^
/git/ome-files-performance/src/main/cpp/pixels-performance.cpp:118:74: error: expected primary-expression before '>' token
                     buf = std::make_unique<ome::files::VariantPixelBuffer>
                                                                          ^
/git/ome-files-performance/src/main/cpp/pixels-performance.cpp:151:64: error: 'make_unique' is not a member of 'std'
             std::unique_ptr<ome::files::FormatWriter> writer = std::make_unique<ome::files::out::OMETIFFWriter>();
                                                                ^
/git/ome-files-performance/src/main/cpp/pixels-performance.cpp:151:111: error: expected primary-expression before '>' token
             std::unique_ptr<ome::files::FormatWriter> writer = std::make_unique<ome::files::out::OMETIFFWriter>();
                                                                                                               ^
/git/ome-files-performance/src/main/cpp/pixels-performance.cpp:151:113: error: expected primary-expression before ')' token
             std::unique_ptr<ome::files::FormatWriter> writer = std::make_unique<ome::files::out::OMETIFFWriter>();
                                                                                                                 ^
src/main/cpp/CMakeFiles/pixels-performance.dir/build.make:62: recipe for target 'src/main/cpp/CMakeFiles/pixels-performance.dir/pixels-performance.cpp.o' failed
make[2]: *** [src/main/cpp/CMakeFiles/pixels-performance.dir/pixels-performance.cpp.o] Error 1
make[1]: *** [src/main/cpp/CMakeFiles/pixels-performance.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:124: recipe for target 'src/main/cpp/CMakeFiles/pixels-performance.dir/all' failed
Makefile:127: recipe for target 'all' failed
The command '/bin/sh -c cmake --build .' returned a non-zero code: 2
```

Am I missing some flags ?

**Comment by mtbc** [comment]
Interesting: ought CI have caught that?

**Comment by sbesson** [comment]
Interestingly https://ci.openmicroscopy.org/view/Experimental/job/OME-FILES-performance-win/ is currently running as expected with the last set of changes. It might be there is a flag in `scripts/jenkins-build.bat` that is missing in the `Dockerfile` (or should we also build JACE with the C++11 flag as this is Linux only)?

**Comment by mtbc** [comment]
Ah, I had made the mistake of looking on the "CPP" tab instead of the "Files" tab in Jenkins.

**Comment by rleigh-codelibre** [comment]
I've pushed a commit to enable C++11/14; does this help?  This was an omission from the cmake build, since this repo originally targetted 0.2.x.

**Comment by sbesson** [comment]
I received the same error when building from https://github.com/snoopycrimecop/ome-files-performance/commit/bd6b24117aabcd80d38dd20a48ce0200566a6954

**Comment by rleigh-codelibre** [comment]
@sbesson Did you remove your setting of CMAKE_CXX_STANDARD from the dockerfile?

**Comment by sbesson** [comment]
@rleigh-codelibre no, I didn't. If this is required as per 08eb7d312940252f9e72a2b031ee15d3efd7d805, can you push the relevant change to this PR?

**Comment by sbesson** [comment]
Tested on Windows (https://ci.openmicroscopy.org/job/OME-FILES-performance-win/119/) and Ubuntu via the Dockerfile, the performance components built as expected and the results are unmodified from the previous runs or slightly improved. Merging.

**Pull request merged**
