### PR TITLE
Add Java basic tiling performance test

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Port the existing C++ benchmark to Java.

Note that until https://trello.com/c/YBsFrE0Q/29-performance-problem-writing-tiles is fixed, the performance will be abysmal.  But the test itself is ready for review and merging.

I can adjust the naming to better match the Java style if needed; it's currently a copy of the C++ code.

Testing: Run `mvn` and then `./scripts/run_basic_tiling`.  You might want to adjust the parameters in the script to make it run a bit faster until TiffSaver is fixed, by dropping some of the test combinations or increasing the step size.

### CODE REVIEW

**Comment by sbesson** [comment]
Now Bio-Formats 5.6.0 is released, we should be able to bump the version in the pom.xml and fix the conflict to start running these tiling benchmarks.

**Comment by sbesson** [comment]
With the latest state of this branch, executed `run_basic_tiling` script with one iteration using the local `/scratch` volume (120G) to store the intermediate data and results. The run highlighted two main issues:

- the first one is related to the writing of a large number of tiles typically the 16x16 tiles case in Java:

   ````
  Java    pixeldata.write 16384-16384-tile-16-16-int16    filesize        83789833        83023458        74290520        8732938
   Java    pixeldata.write 16384-16384-tile-1312-1312-int16        filesize        6399    6321    5850    471
   ````
   As mentioned by @rleigh-codelibre, the per-tile overhead currently scales with N*2. While writing 16K x 16K images using 16x16 tiles is probably not something we would recommend, for large images e.g. 100x200K, this effect would however be significant when using typically 128x128 tiles.

- a secondary issue is related to the design of these benchmark. For each pixeltype, files are written for all the possible tile sizes to disk before being cleared. In the current setup, this fills the volume aborting the benchmark:

    ```
    TEST: [0] 16384-16384-tile-384-384-uint32
    TEST: [0] 16384-16384-tile-1392-1392-uint32
    Error: caught exception: java.io.IOException:
    ```

   Using a NFS mount with more storage space is a possibility but might affect the performance of the metrics. If running these benchmarks on local storage is a requirement, are there options in terms of test architecture to clean intermediate results at more regular intervals? /cc @manics @joshmoore

**Comment by manics** [comment]
What aspect of performance are you most interested in- CPU, memory, or disk IO?

**Comment by sbesson** [comment]
As discussed yesterday, a single iteration of the test is currently been executed on `minke` with more disk space available for the temporary results. Once completed to succession, we can aggregate the results from both languages and get this merged. For the performance issue with large number of tiles, what are the next steps for we identifying the bottleneck in the Java code @rleigh-codelibre?

**Comment by rleigh-codelibre** [comment]
Why are we coupling *writing* the tests and *running* the tests to the PR review process within a single PR?  Why can't we get the tests working, and then run them and add the final results/analysis as two separate steps?  Having a single PR open for so long causes logistical problems with conflicts as well as making it hard for others to work on the tests at the same time.

Regarding next steps, https://github.com/ome/ome-common-java/pull/15 is likely worth testing with the existing test to evaluate its performance, though there may well be more we can do in addition to this change.

**Comment by sbesson** [comment]
Agreed about trying to get this PR merged and move forward with the next steps. As mentioned above, the main blocker is that I have not been able to complete the instructions in this PR description i.e. get a full run of `run_basic_tiling` passing.

Given the time, aborting the running benchmark and reducing the tiling parameter to start from 128 and increase by steps of 128 (unless there is a better suggestion) and will comment here as soon as this is done.

**Comment by rleigh-codelibre** [comment]
Sounds great, thanks.

**Comment by sbesson** [comment]
With the following changes:

```
no changes added to commit (use "git add" and/or "git commit -a")
root@ce3b33780439:/git/ome-files-performance# git diff
diff --git a/scripts/run_basic_tiling b/scripts/run_basic_tiling
index ea67fd7..5c3a04c 100755
--- a/scripts/run_basic_tiling
+++ b/scripts/run_basic_tiling
@@ -3,20 +3,20 @@ set -e
 set -x
 
 datapath="/data"
-binpath="/tmp/bm/src/main/cpp"
+binpath="/install/bin"
 resultpath="${datapath}/results"
 outpath="${datapath}/out"
-iterations=10
+iterations=1
 imagesizex=16384
 imagesizey=16384
 bigimagesizex=65536
 bigimagesizey=65536
-tilesizestart=16
+tilesizestart=128
 tilesizeend=2048
-tilesizeincrement=16
-stripsizestart=1
+tilesizeincrement=128
+stripsizestart=4
 stripsizeend=256
-stripsizeincrement=1
+stripsizeincrement=4
 pixeltypes="uint8 int16 uint32 float"
 
 # Clean results folder
```

the benchmark ran to completion in a reasonable time. A few comments from the generated output:

- we have no Java equivalents of the C+ strip tests
- the Java results are overwritten by the C++ run
- as mentioned by @manics, it would be useful to update https://github.com/openmicroscopy/ome-files-performance/blob/master/doc/basic-tile-performance.md to document the requirements in terms of disk space for the full benchmark

None of these are blockers to this if we want to get this merged. We can review these points in follow-up PRs.

**Pull request merged**
